version: '3'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: project
      MONGO_INITDB_ROOT_PASSWORD: 'pass123'
    ports:
      - '27017:27017'

  app:
    depends_on:
      - mongo
    container_name: project
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
    ports:
      - '3001:3001'